// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHin_AhjxR-9kHufd96joOkKW1y6bw5G8',
    appId: '1:133382258332:web:f9189921fb5aa040803759',
    messagingSenderId: '133382258332',
    projectId: 'water-reminder-fd524',
    authDomain: 'water-reminder-fd524.firebaseapp.com',
    databaseURL: 'https://water-reminder-fd524-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-reminder-fd524.firebasestorage.app',
    measurementId: 'G-S3MKEVG772',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmUbneFnBP3vXmfBqPtddn3U5k0uHtmTI',
    appId: '1:133382258332:android:34e7ef7739086f67803759',
    messagingSenderId: '133382258332',
    projectId: 'water-reminder-fd524',
    databaseURL: 'https://water-reminder-fd524-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-reminder-fd524.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFvMDgYt9HZJKbOUPAoKpWMcwHFVsVCsM',
    appId: '1:133382258332:ios:1b810dcd05451787803759',
    messagingSenderId: '133382258332',
    projectId: 'water-reminder-fd524',
    databaseURL: 'https://water-reminder-fd524-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-reminder-fd524.firebasestorage.app',
    androidClientId: '133382258332-bsert09ut4bbahr9h8chf68d6mjohd38.apps.googleusercontent.com',
    iosClientId: '133382258332-nv8jif623kupjjs2q6lr5oos27dgrtv9.apps.googleusercontent.com',
    iosBundleId: 'com.nazerapps.waterreminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFvMDgYt9HZJKbOUPAoKpWMcwHFVsVCsM',
    appId: '1:133382258332:ios:1b810dcd05451787803759',
    messagingSenderId: '133382258332',
    projectId: 'water-reminder-fd524',
    databaseURL: 'https://water-reminder-fd524-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-reminder-fd524.firebasestorage.app',
    androidClientId: '133382258332-bsert09ut4bbahr9h8chf68d6mjohd38.apps.googleusercontent.com',
    iosClientId: '133382258332-nv8jif623kupjjs2q6lr5oos27dgrtv9.apps.googleusercontent.com',
    iosBundleId: 'com.nazerapps.waterreminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHin_AhjxR-9kHufd96joOkKW1y6bw5G8',
    appId: '1:133382258332:web:93023fd12b41b9d1803759',
    messagingSenderId: '133382258332',
    projectId: 'water-reminder-fd524',
    authDomain: 'water-reminder-fd524.firebaseapp.com',
    databaseURL: 'https://water-reminder-fd524-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-reminder-fd524.firebasestorage.app',
    measurementId: 'G-E9NB7WKB7X',
  );
}
